kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
spec:
  selector:
    app:  mongo-express
  type: LoadBalancer
  ports:
  - name: externalport
    port:  8081
    targetPort:  8081
    protocol: TCP
    nodePort: 30000
